### ISSUE TITLE
please add  walnuts

### ISSUE THREAD

**Issue by 20308ASHISH** [20308ASHISH/intro-to-github#2]
** good add **
![46](https://user-images.githubusercontent.com/102867894/161395578-fc330ded-878a-4b36-bb6e-1866dc2bad9b.jpg)

**Comment by 20308ASHISH** [comment]
i have fixed https://github.com/20308ASHISH/intro-to-github/commit/69b957a2eff773d57ede10c61c096dd9a9b7fc59

**Comment by ashwanimishra404** [comment]
HELLO BHAIYA

**Comment by ashwanimishra404** [comment]
KAHA HO KYA KAR RAHE HO
